### ISSUE TITLE
Forslag: Disallow commits direkte til master (og evt dev) branchen - kun lov med merges 

### ISSUE THREAD

**Issue by BeatsuDev** [isakjonsson1/Legoteam-8#12]
Akkurat nå er det lett å glemme seg og pushe commits direkte til master branch eller dev branch. Dette skal uansett ikke være mulig og hvis dette skaper issues er det et større pain å fikse og vi har ingen backup. Egentlig så skal nye endringer i koden lages i egne branches før det merges til dev (sjekk bildet under). Det er ikke like farlig med dev branchen, men ihvertfall på master branchen synes jeg vi bør forby direkte commits og kun tillate merges (fra dev). 

![image](https://user-images.githubusercontent.com/35773677/141019209-702a81f5-5ed7-4628-b3a5-5718d6e47f2b.png)

Derfor foreslår jeg at vi forbyr å pushe til master direkte med [denne implementasjonen f.eks.](https://stackoverflow.com/questions/40462111/prevent-commits-in-master-branch), og vurdere å gjøre det samme med dev (opp til hva dere synes). Det er litt mer styr, men det er sånn det blir på større prosjekter senere er jeg ganske sikker på. Det blir veldig neat og ryddig!! ~~(I tillegg gir det oss mer å lære og mer tid vi kan skrive opp i time-lista 😎)~~

**Comment by BeatsuDev** [comment]
Update: det kan godt hende dette bare er en lokal ting og ikke kan implementeres for alle... Må lese opp mer på pre-commits og relevante temaer.

**Comment by BeatsuDev** [comment]
Update: Det er en instilling i GitHub for å gjøre noen branches "protected". @isakjonsson1 må endre på innstillingen eller eventuelt legge oss til som admministratorer: https://stackoverflow.com/questions/46146491/prevent-pushing-to-master-on-github.

Kan vi sette opp dette på både master og dev branchen? Fra nå av så må vi lage nye branches uansett endringer vi skal gjøre.

**Comment by BeatsuDev** [comment]
Husk også å checke "Include administrators" slik at det gjelder administratorer også

**Comment by BeatsuDev** [comment]
Kan også lese mer opp på det her for de som er interesserte (har ikke lest selv, men virker interessant og leser det kanskje senere): https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches

**Comment by BeatsuDev** [comment]
@isakjonsson1 Har du skrudd av "Require approvals" under samme setting?

**Comment by isakjonsson1** [comment]
Gjorde det nå @BeatsuDev
