### ISSUE TITLE
Optimize image parsing - 72 sekunder til 30 sekunder?

### ISSUE THREAD

**Issue by BeatsuDev** [isakjonsson1/Legoteam-8#13]
Akkurat nå så bruker robotten 72 sekunder å parse en svg fil. Jeg vil helst ha litt hår igjen til etter prosjektet er over, og vil ikke rive ut alt av å ha glemt en indent et sted og ikke finne ut før ~80 sekunder etter kjøring - HVER JÆVLA GANG.

Så kanskje vi kan ha som mål å få det ned til under 30 sekunder? Klarer vi det? 🤩 Et godt startpunkt å lese seg opp på hvordan man optimaliserer kode er her (tatt direkte fra MICROpython documentation (viktig at det er micropython, fordi mange libraries er ikke tatt med)): https://docs.micropython.org/en/latest/reference/speed_python.html?highlight=profile

**Comment by BeatsuDev** [comment]
@Kaholaz Du sa at isinstance brukte lang tid ikke sant? Sjekk ut duck-typing https://docs.python.org/3.5/glossary.html#term-duck-typing Leste nettopp på det, og det virker nice for å implementere checks, men samtidig gjøre sjekken mye raskere. 

> If it looks like a duck and quacks like a duck, it must be a duck.

**Comment by Kaholaz** [comment]
Det går bra sånn det er nå. Jeg fjerna alle sjekkene nå, og det eneste som vil skje om noe feil blir brukt er AttributeError eller ValueError. Siden metodene bare brukes på en type og sjekkene bare var der for å sørge for at man ikke passa inn en annen type, er det ikke noe stress å fjerne sjekkene.

**Comment by Kaholaz** [comment]
@BeatsuDev koden er ganske optimalisert nå, hvis dette ikke holder, tror jeg det er lettere å skru ned samling raten når kurvene genererer look up tables

**Comment by BeatsuDev** [comment]
![image](https://user-images.githubusercontent.com/35773677/141092169-b9bc9361-83de-4adb-bb4a-3022745afed0.png)

Det er look-up tablesene som bruker mest tid i følge profileren, så det kan speede det opp ganske mye.

**Comment by BeatsuDev** [comment]
Fikk parsing under 20 sek ved å blant annet fjerne sjekk med isinstance og bruke math.sqrt istedenfor .length metoden i hvert punkt. Lukket issue med merge #15
