### ISSUE TITLE
Robotten kjører ikke riktig i svinger

### ISSUE THREAD

**Issue by BeatsuDev** [isakjonsson1/Legoteam-8#16]
Robotten - av ukjente grunner - kjører ikke riktig i svinger. Det virker som at den er avhengig av farten, noe den ikke burde være (større hastighet gir større utslag i rotasjon). 

- [x] ~~Sjekk om farten har noe å si~~ | Det har den.
- [x] ~~Prøv å kalkulere distansen tidsbasert (dersom problemet ligger i målingen av distanse i svinger)~~ | Fortsatt samme problem
- [x] ~~Kjør en simulasjon for å sjekke om matten bak det er riktig ([ref branch](https://github.com/isakjonsson1/Legoteam-8/tree/turtle))~~ | Etter noen justeringer, viser simulasjonen at robotten burde kjøre riktig. Pga unøyaktighet fungerer ikke robotten som den skal.

**Comment by BeatsuDev** [comment]
Simulasjonene i turtle viser at robotten burde kjøre riktig og at det er unøyaktighetene i sensorene og motorene som gjør at den ikke kjørere riktig. Av den grunn, kjører vi kun rette linjer i demonstrasjonen og skylder på unøyaktige sensorer og motorer for å gjøre dette problemet nærmest umulig å fikse.

**Comment by Kaholaz** [comment]
Etter simuleringen ser det ikke ut til at problemet har noe med vår implementasjon å gjøre, men med unøyaktigheter i selve ev3 roboten. Problemet er dermed ikke noe vi kan utbedre. Issuen blir som en konsekvens dermed stengt
