### ISSUE TITLE
Pen motor fungerer ikke i det hele tatt

### ISSUE THREAD

**Issue by BeatsuDev** [isakjonsson1/Legoteam-8#17]
Pennen går for langt ned og kan dytte robotten oppover/skape ekstra friksjon som igjen skaper problemer for kjøringen. I tillegg kan det hende at pennen løftes oppover når den egentlig skal nedover - og motsatt.

**Comment by aaarunan** [comment]
Enig
Skal fikse det. Ser ikke ut til at den vet statusen til pen_motor, fordi motoren bli veldig varm og dreper batteriet.

**Comment by BeatsuDev** [comment]
Kan være bedre å bruke run_angle istedenfor run_target. run_angle roterer 90 grader relativt til rotasjonen den har nå. run_target roterer helt til rotasjonen er angitt grader
