### ISSUE TITLE
Mulighet til å bestemme filer som skal tegnes/kjøres/plottes fra kommandolinjen

### ISSUE THREAD

**Issue by Kaholaz** [isakjonsson1/Legoteam-8#22]
Per nå er det kun mulig å endre fil som parses ved å endre på kildekoden. Dette er strevsomt og kan føre til teite merge konflikter etterhvert. Derfor tenker jeg at det er lurt å gjøre det slik at man kan bestemme filen(e) som skal parses ved å skrive in filnavnet (uten .svg?) som et commandolinjeargument.

Dette er lurt å gjøre for å øke brukervennligheten og funksjonaliteten til CLIet vårt.

**Comment by BeatsuDev** [comment]
Enig! Virker som noe ikke så vanskelig å implementere også

**Comment by Kaholaz** [comment]
Denne issuen jobbes med i [CLI branchen](https://github.com/isakjonsson1/Legoteam-8/tree/CLI)
